name: Update TIME

on:
  schedule:
    - cron: '0 0 5 * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update TIME
        run: python update_time.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update README with years since inscription'
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/Juliendnte/Juliendnte.git HEAD:main
